[2022-03-23 03:51:02,799] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: boston_service_request_csv.csv_to_gcs_job 2019-06-02T06:00:00+00:00 [queued]>
[2022-03-23 03:51:02,840] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: boston_service_request_csv.csv_to_gcs_job 2019-06-02T06:00:00+00:00 [queued]>
[2022-03-23 03:51:02,842] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 03:51:02,843] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-23 03:51:02,845] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 03:51:02,873] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): csv_to_gcs_job> on 2019-06-02T06:00:00+00:00
[2022-03-23 03:51:02,882] {standard_task_runner.py:52} INFO - Started process 704 to run task
[2022-03-23 03:51:02,892] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'boston_service_request_csv', 'csv_to_gcs_job', '2019-06-02T06:00:00+00:00', '--job-id', '142', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/boston_service_request.py', '--cfg-path', '/tmp/tmpzvoix6ec', '--error-file', '/tmp/tmpwtct6k7r']
[2022-03-23 03:51:02,902] {standard_task_runner.py:77} INFO - Job 142: Subtask csv_to_gcs_job
[2022-03-23 03:51:03,012] {logging_mixin.py:104} INFO - Running <TaskInstance: boston_service_request_csv.csv_to_gcs_job 2019-06-02T06:00:00+00:00 [running]> on host 294e23567a6c
[2022-03-23 03:51:03,139] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=boston_service_request_csv
AIRFLOW_CTX_TASK_ID=csv_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2019-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-06-02T06:00:00+00:00
[2022-03-23 03:51:03,263] {taskinstance.py:1455} ERROR - [Errno 2] No such file or directory: '/opt/airflow/output_2019-06.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/boston_service_request.py", line 38, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2473, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_2019-06.csv'
[2022-03-23 03:51:03,281] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=boston_service_request_csv, task_id=csv_to_gcs_job, execution_date=20190602T060000, start_date=20220323T035102, end_date=20220323T035103
[2022-03-23 03:51:03,361] {local_task_job.py:146} INFO - Task exited with return code 1
