[2022-03-19 18:05:42,567] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: 311_service_request_dag.upload_to_gcs_job 2022-03-17T13:29:34.380568+00:00 [queued]>
[2022-03-19 18:05:42,603] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: 311_service_request_dag.upload_to_gcs_job 2022-03-17T13:29:34.380568+00:00 [queued]>
[2022-03-19 18:05:42,605] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 18:05:42,606] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2022-03-19 18:05:42,607] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-19 18:05:42,629] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): upload_to_gcs_job> on 2022-03-17T13:29:34.380568+00:00
[2022-03-19 18:05:42,637] {standard_task_runner.py:52} INFO - Started process 450 to run task
[2022-03-19 18:05:42,647] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', '311_service_request_dag', 'upload_to_gcs_job', '2022-03-17T13:29:34.380568+00:00', '--job-id', '74', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/311_download_ingest_gcs.py', '--cfg-path', '/tmp/tmpp0omcu4k', '--error-file', '/tmp/tmpim0dsvv9']
[2022-03-19 18:05:42,654] {standard_task_runner.py:77} INFO - Job 74: Subtask upload_to_gcs_job
[2022-03-19 18:05:42,734] {logging_mixin.py:104} INFO - Running <TaskInstance: 311_service_request_dag.upload_to_gcs_job 2022-03-17T13:29:34.380568+00:00 [running]> on host 22873fda35af
[2022-03-19 18:05:42,824] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=311_service_request_dag
AIRFLOW_CTX_TASK_ID=upload_to_gcs_job
AIRFLOW_CTX_EXECUTION_DATE=2022-03-17T13:29:34.380568+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-17T13:29:34.380568+00:00
[2022-03-19 18:05:43,252] {taskinstance.py:1455} ERROR - ('invalid_grant: Invalid JWT Signature.', '{"error":"invalid_grant","error_description":"Invalid JWT Signature."}')
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/311_download_ingest_gcs.py", line 53, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2487, in upload_from_filename
    checksum=checksum,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2360, in upload_from_file
    checksum=checksum,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2182, in _do_upload
    checksum=checksum,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 1733, in _do_multipart_upload
    transport, data, object_metadata, content_type, timeout=timeout
  File "/home/airflow/.local/lib/python3.6/site-packages/google/resumable_media/requests/upload.py", line 146, in transmit
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/resumable_media/requests/_request_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/resumable_media/_helpers.py", line 175, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/transport/requests.py", line 477, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/service_account.py", line 377, in refresh
    request, self._token_uri, assertion
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/_client.py", line 153, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', '{"error":"invalid_grant","error_description":"Invalid JWT Signature."}')
[2022-03-19 18:05:43,270] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=311_service_request_dag, task_id=upload_to_gcs_job, execution_date=20220317T132934, start_date=20220319T180542, end_date=20220319T180543
[2022-03-19 18:05:43,318] {local_task_job.py:146} INFO - Task exited with return code 1
